package com.hanyang.startup.hanyangstartup.resource.domain;

public enum FILE_DIVISION {
    BOARD_THUMB_IMG,
    BOARD_CONTENT_IMG,
    BOARD_ATTACH,
    NOTICE_ATTACH,
    NOTICE_CONTENT_ATTACH,
    MENTORING_ATTACH,
    MENTORING_ANSWER_ATTACH,
    STUDENT_ATTACH,
    PROFILE_IMG,
    MENTOR_PROFILE_IMG,
    PLACE_IMG,
    ROOM_IMG,
    POPUP_IMG,
    STARTUP_LOGO,
    PARTNER_LOGO
}
